// ds-prompt.mjs — render the per-load "design-system prompt" (_ds_prompt.md)
// that import-design-system.mjs drops into _ds/<slug>/. It mirrors the web
// product's injected <attached-skill name="… (design system)"> block, adapted
// to the portable layout: project-relative `_ds/<slug>/` paths for the runtime
// copy and the recorded `sourcePath` for the system's source (mocks/ui_kits).
//
// Pure string assembly — writes nothing. Reused by the importer and any future
// regen script/skill.

const SCOPE =
  'Scope: the design system is a visual style reference only. Its guide may describe ' +
  'example products, brands, or people unrelated to the user and to the subject of this ' +
  'conversation. Never treat anything in the design system as a fact about the user, their ' +
  'work, or the topic.';

export function renderDsPrompt({
  name,
  slug,
  namespace,
  cssEntry,
  sampleComponent,
  readme,
  tokenNames,
  sourcePath,
  hasBundle,
} = {}) {
  const dsName = name || slug || 'this';
  const out = [];
  out.push(
    '<!-- Generated by import-design-system.mjs — regenerate by re-running the import. Do not hand-edit. -->',
  );
  out.push('');
  out.push(
    `[Design System] This project uses the **${dsName}** design system. This is a binding ` +
    "choice for visual style — every visual must follow it. Don't invent colors, type, " +
    'spacing, or components not grounded here.',
  );
  out.push('');
  out.push(SCOPE);
  out.push('');
  out.push('Explore it to find what you need:');
  out.push('- Always copy out the fonts and colors you need');
  out.push('- For prototypes and designs, always copy out any relevant components');
  out.push(
    '- If it ships mocks of existing products and you were asked to design something similar, ' +
    'copy and fork those mocks to start.',
  );

  // wiring — only the lines that apply
  const wiring = [];
  if (cssEntry) wiring.push(`  <link rel="stylesheet" href="_ds/${slug}/${cssEntry}">`);
  if (hasBundle) wiring.push(`  <script src="_ds/${slug}/_ds_bundle.js"></script>`);
  if (hasBundle && namespace) {
    wiring.push(`  then in a Babel script: const { ${sampleComponent || 'Button'} } = window.${namespace};`);
  }
  if (wiring.length) {
    out.push('');
    out.push(`Wiring — imported under \`_ds/${slug}/\` (load the PRIMARY system's <link> LAST so its tokens win):`);
    out.push(...wiring);
  }

  // full guide, inlined (raw — this is a .md file, not embedded HTML)
  if (readme && readme.trim()) {
    out.push('');
    out.push("Full guide reproduced below so you don't need to fetch it:");
    out.push('');
    out.push('<design-system-guide>');
    out.push(readme.trim());
    out.push('</design-system-guide>');
  }

  // token allowlist — the enforceable guardrail
  const names = Array.isArray(tokenNames)
    ? [...new Set(tokenNames.filter(Boolean))].sort()
    : [];
  if (names.length) {
    const where = cssEntry ? `\`_ds/${slug}/${cssEntry}\`` : "the system's stylesheet";
    out.push('');
    out.push(
      `CSS tokens: the exact \`--*\` names are defined in ${where}. The ${names.length} ` +
      'custom properties it defines are:',
    );
    out.push('');
    out.push(names.join(', '));
    out.push('');
    out.push(
      'Only use `var(--*)` names from that list. Never guess a token name — an unresolved ' +
      '`var()` silently falls back to the browser default.',
    );
  }

  // source for mocks / specimens / component source
  if (sourcePath) {
    out.push('');
    out.push(
      'For assets and UI kits beyond the guide (mocks to fork, specimens, component source): ' +
      `read from the system's source at \`${sourcePath}/\` (e.g. \`${sourcePath}/ui_kits/\`, ` +
      `\`${sourcePath}/preview/\`) and copy what you need into this project.`,
    );
  }

  return out.join('\n') + '\n';
}

export default renderDsPrompt;
